---
title: 'COVID-19 Random State: Nevada'
author: "David J Jackson"
date: "8/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSQLite)
```
```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
```

```{r}
# PUll State level data
VI <- dbGetQuery(db,"select date,state,TotalCases,TotalDeaths,new_cases,new_deaths from  STATESDAILY where state='Iowa'")
VI$date <- as.Date(VI$date)
VI$date <- sort(VI$date,decreasing = TRUE)
str(VI)

## County Data
DF <- dbGetQuery(db,"select date,state,county,new_cases,new_deaths from  COUNTYDAILY where state='Iowa'")
DF$date <- as.Date(DF$date)
str(DF$date)
```

## Plot Daily New Cases and New Deaths 
####  Cumulative Total Cases and Deaths

```{r}
plot(VI$date,VI$TotalCases,type="l",main="Cumulative Cases")
grid(col="black")
plot(VI$date,VI$TotalDeaths,type="l",main="Cumulative Deaths")
grid(col="black")
```

####  Total Cases, Total Deaths (w/ 14 Day Moving Avearge) by Date

```{r}
VI$MAC <- movingAverage(VI$new_cases,14)
VI$MAD <- movingAverage(VI$new_deaths,14)
plot(VI$date,VI$new_cases,type="l",main="Total Cases by Date",col="black")
lines(VI$date,VI$MAC,col="red")
grid(col="black")
plot(VI$date,VI$new_deaths,type="l",main="Total Deaths by Date")
lines(VI$date,VI$MAD,col="red")
grid(col="black")
```

#### Weekly  New Cases and New Deaths.

```{r}
VI$Monthly <- as.Date(cut(VI$date,
  breaks = "month"))
VI$Weekly <- as.Date(cut(VI$date,
  breaks = "week",
  start.on.monday = FALSE)) # changes weekly break point to Sunday

```

```{r}
weekly_cases <- aggregate(new_cases~Weekly,data=VI,FUN=sum)
weekly_deaths <- aggregate(new_deaths~Weekly,data=VI,FUN=sum)
weekly_cases$RCases <- weekly_deaths$new_deaths / weekly_cases$new_cases *100
```

```{r}
barplot(new_cases ~Weekly,data=weekly_cases,main="Weekly COVOD-19 Cases",xlab="Weekly Date",ylab="Cases")
grid(col="black")

barplot(new_deaths ~Weekly,data=weekly_deaths,main="Weekly COVID-19 Deaths",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")

barplot(RCases ~Weekly,data=weekly_cases,main="Weekly COVID-19 Death Rate",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")
```

### Total New Cases and Deaths from Jun. 1, 2020 - Present

```{r}
df <- subset(VI,date >="2020-06-01")
plot(df$date,df$new_cases,type="l",main="Daily New Cases")
grid(col="black")

plot(df$date,df$new_deaths,type="l",main="Daily New Deaths")
grid(col="black")
```

### Top 5 countries by Single day totals for Aug. 26, 2020

```{r}
df <- subset(DF,date =="2020-08-29" )
df$new_cases <- sort(df$new_cases,decreasing=TRUE)
df_cases <-head(df,n=5)
barplot(new_cases ~county,data=df_cases,main="Top 5 States Ranked by single Day Cases",xlab="(For August 26, 2020)",ylab="Cases")
grid(col="black")


df$new_deaths <- sort(df$new_deaths,decreasing=TRUE)
df_deaths <-head(df,n=5)
barplot(new_deaths ~county,data=df_deaths,main="Top 5 States Ranked by single Day Deaths",xlab="(For August 27, 2020)",ylab="Cases")
grid(col="black")
```

