---
title: 'COVID19: New Hampshire Random State'
author: "David RJ Jackson"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(RSQLite)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))

```
```{r}
rm(list=ls())
db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")

VI <- dbGetQuery(db,"select date,state,TotalCases,TotalDeaths,new_cases,new_deaths from  STATESDAILY where state='New Hampshire'")
VI$date <- as.Date(VI$date)
VI <-  VI[order(VI$date),]
summary(VI$new_cases)
summary(VI$new_deaths)
```

### Cumulative Cases and Deaths

```{r}
ggplot(VI) + geom_line(aes(x=date,y=TotalCases ),col="red") +
  labs(title="Cumulative Cases by Date") +
  scale_y_continuous(labels = scales::comma)

ggplot(VI) + geom_line(aes(x=date,y=TotalDeaths ),col="red") +
  labs(title="Cumulative  Deaths by Date") +
  scale_y_continuous(labels = scales::comma) 
  
```


### Total Cases and Deaths by Date

```{r}
ggplot(VI) + geom_line(aes(x=date,y=new_cases,col="Daily Cases")) +
  labs(title=" Cases by Date") +
  geom_smooth(aes(x=date,y=new_cases,col="Loess"),span=0.25) 
  

ggplot(VI) + geom_line(aes(x=date,y=new_deaths,col="Daily Deaths")) +
   labs(title=" Deaths by Date") +
  geom_smooth(aes(x=date,y=new_deaths,col="Loess"),span=0.25) 
  
```

### Death Rate as Percent "%" by Day

```{r}
VI$Rate <- VI$new_deaths/VI$new_cases
VI <- subset(VI,date>="2020-04-01" & Rate >=0)
ggplot(VI) + geom_line(aes(x=date,y=Rate)) +
  scale_y_continuous(labels = scales::percent) +
  labs(title="Daily Mortality Rate",
       y="Mortality Rate %") +
  geom_hline(yintercept = mean(VI$Rate),col="red") 
```

### Weekly and MOnthly Cases and Deaths

```{r}
VI$Monthly <- as.Date(cut(VI$date,
  breaks = "month"))
VI$Weekly <- as.Date(cut(VI$date,
  breaks = "week",
  start.on.monday = FALSE)) # changes weekly break point to Sunday

```

```{r}

weekly_cases <- aggregate(new_cases~Weekly,data=VI,FUN=sum)
weekly_deaths <- aggregate(new_deaths~Weekly,data=VI,FUN=sum)
# weekly_cases$RCases <- weekly_deaths$new_deaths / weekly_cases$new_cases *100
```
```{r}
weekly <- subset(weekly_cases, new_cases >=0)
ggplot(weekly) + geom_col(aes(x=Weekly,y=new_cases)) +
  labs(title="Total Cases by Week") 
  

ggplot(weekly_deaths) + geom_col(aes(x=Weekly,y=new_deaths)) +
  labs(title="Total Deaths by Week")
```

#### Monthly Numbers

```{r}
monthly_cases <- aggregate(new_cases~Monthly,data=VI,FUN=sum)
monthly_deaths <- aggregate(new_deaths~Monthly,data=VI,FUN=sum)

```
```{r}
ggplot(monthly_cases) + geom_col(aes(x=Monthly,y=new_cases)) +
  labs(title="Total Cases by Month")

ggplot(monthly_deaths) + geom_col(aes(x=Monthly,y=new_deaths)) +
  labs(title="Total Deaths by Month")
```