---
title: 'COVID-19 Random States : New Jersey'
author: "David J Jackson"
date: "8/22/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
df <- read.csv("./New-Jersey.csv")
df$date <- as.Date(df$date,format="%Y-%m-%d")
df$date <-sort(df$date)
colnames(df) <-c("Date","State","Cases","Deaths","DailyCases","DailyDeaths")
```

### Plot of Cumulative coID-19 Cases and Deaths for New Jersey

```{r}
plot(df$Date,df$Cases,type="l",main="Cumulative coID-19 Cases")
grid(col="black")

plot(df$Date,df$Deaths,type="l",main="Cumulative coID-19 Deaths")
grid(col="black")
```

### Plot of Daily COVID-19 Cases and Deaths for New Jersey

```{r}
plot(df$Date,df$DailyCases,type="l",main="Daily coID-19 Cases")
grid(col="black")

plot(df$Date,df$DailyDeaths,type="l",main="Daily coID-19 Deaths")
grid(col="black")
```

## Plotting of Loess Smooth Curve for Cases and Deaths

```{r}
df$index <- 1:nrow(df)
loess1 <- loess(df$DailyCases~df$index)
loess2 <- loess(df$DailyCases~df$index,span=0.25)
loess3 <- loess(df$DailyCases~df$index,span=0.50)
loess4 <- loess(df$DailyCases~df$index,span=0.75)

```
```{r}
df$sm00 <- predict(loess1) 
df$sm25 <- predict(loess2) 
df$sm50 <- predict(loess3)
df$sm75 <- predict(loess4)

```
```{r}
plot(df$Date,df$DailyCases,type="l",main="Daily coID-19 Cases (defualt)")
lines(df$Date,df$sm00,col="red")


plot(df$Date,df$DailyCases,type="l",main="Daily coID-19 Cases(0.25)")
lines(df$Date,df$sm25,col="red")
grid(col="black")

plot(df$Date,df$DailyCases,type="l",main="Daily coID-19 Cases(0.50)")
lines(df$Date,df$sm50,col="red")
grid(col="black")

plot(df$Date,df$DailyCases,type="l",main="Daily coID-19 Cases(0.75)")
lines(df$Date,df$sm75,col="red")
grid(col="black")
```
```{r}
df$index <- 1:nrow(df)
loess25 <- loess(df$DailyDeaths~df$index,span=0.25)
df$sm25 <- predict(loess25)

plot(df$Date,df$DailyDeaths,type="l",main="Daily coID-19 Deaths(0.25)")
lines(df$Date,df$sm25,col="red")
grid(col="black")
```

### Weekly and Monthly Cases and Deaths

```{r}
df$Monthly <- as.Date(cut(df$Date,
  breaks = "month"))
df$Weekly <- as.Date(cut(df$Date,
  breaks = "week",
  start.on.monday = FALSE)) # changes weekly break point to Sunday

```

```{r}
weekly_cases <- aggregate(DailyCases~Weekly,data=df,FUN=sum)
weekly_deaths <- aggregate(DailyDeaths~Weekly,data=df,FUN=sum)
```

```{r}
barplot(DailyCases ~Weekly,data=weekly_cases,main="Weekly COVOD-19 Cases",xlab="Weekly Date",ylab="Cases")
grid(col="black")

barplot(DailyDeaths ~Weekly,data=weekly_deaths,main="Weekly COVID-19 Deaths",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")
```


```{r}
monthly_cases <- aggregate(DailyCases~Monthly,data=df,FUN=sum)
monthly_deaths <- aggregate(DailyDeaths~Monthly,data=df,FUN=sum)
```

```{r}
barplot(DailyCases ~Monthly,data=monthly_cases,main="Monthly COVOD-19 Cases",xlab="MonthlyDate",ylab="Cases")
grid(col="black")

barplot(DailyDeaths ~Monthly,data=monthly_deaths,main="Monthly COVID-19 Deaths",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")
```


