---
title: 'COVID-19 Random State: North Carolina'
author: "David J Jackson"
date: "8/23/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv("./NorthCarolina.csv")
df$date <- as.Date(df$date,format="%Y-%m-%d")
df$date <- sort(df$date,decreasing = FALSE)
```

#### Plot of Cumulative Cases and Deaths(Mar.3,2020 - Aug. 22,2020)

```{r}
plot(df$date,df$cases,type="l",main="Cumulative Cases")
grid(col="black")
plot(df$date,df$deaths,type="l",main="Cumulative Deaths")
grid(col="black")
```

####  Plots of Daily New Cases and New Deaths(Mar. 3,2020 - Aug. 22,2020)

```{r}
df$index <- 1:nrow(df)
loess1 <- loess(df$DailyCases~df$index)
loess2 <- loess(df$DailyCases~df$index,span=0.25)
loess3 <- loess(df$DailyCases~df$index,span=0.50)
loess4 <- loess(df$DailyCases~df$index,span=0.75)

```
```{r}
df$sm00 <- predict(loess1) 
df$sm25 <- predict(loess2) 
df$sm50 <- predict(loess3)
df$sm75 <- predict(loess4)
```
```{r}
plot(df$date,df$DailyCases,type="l",main="Daily COVID-19 Cases (defualt)",col="black")
lines(df$date,df$sm00,col="red")
grid(col="black")
legend("topleft",
       c("Daily Deaths","Loess"),
       col=c("black","red"),
       lty = c(1, 1),
       cex = 0.8)

plot(df$date,df$DailyCases,type="l",main="Daily COVID-19 Cases(0.25)",col="black")
lines(df$date,df$sm25,col="red")
grid(col="black")
legend("topleft",
       c("Daily Deaths","Loess"),
       col=c("black","red"),
       lty = c(1, 1),
       cex = 0.8)

plot(df$date,df$DailyCases,type="l",main="Daily COVID-19 Cases(0.50)",col="black")
lines(df$date,df$sm50,col="red")
grid(col="black")
legend("topleft",
       c("Daily Deaths","Loess"),
       col=c("black","red"),
       lty = c(1, 1),
       cex = 0.8)

# plot(df$date,df$DailyCases,type="l",main="Daily COVID-19 Cases(0.75)")
# lines(df$date,df$sm75,col="red")
# grid(col="black")
```
```{r}
### Daily Loess for Deaths
df$index <- 1:nrow(df)
loess10 <- loess(df$DailyDeaths~df$index)
loess25 <- loess(df$DailyDeaths~df$index,span=0.25)
loess50 <- loess(df$DailyDeaths~df$index,span=0.50)
loess75 <- loess(df$DailyCases~df$index,span=0.75)

```
```{r}
df$sm00 <- predict(loess10) 
df$sm25 <- predict(loess25) 
df$sm50 <- predict(loess50)
df$sm75 <- predict(loess75)
```
```{r}
plot(df$date,df$DailyDeaths,type="l",main="Daily COVID-19 Deaths (defualt)",col="black")
lines(df$date,df$sm00,col="red")
grid(col="black")
legend("topleft",
       c("Daily Deaths","Loess"),
       col=c("black","red"),
       lty = c(1, 1),
       cex = 0.8)

plot(df$date,df$DailyDeaths,type="l",main="Daily COVID-19 Deaths(0.25)",col="black")
lines(df$date,df$sm25,col="red")
grid(col="black")
legend("topleft",
       c("Daily Deaths","Loess"),
       col=c("black","red"),
       lty = c(1, 1),
       cex = 0.8)

plot(df$date,df$DailyDeaths,type="l",main="Daily COVID-19 Deaths(0.50)",col="black")
lines(df$date,df$sm50,col="red")
grid(col="black")
legend("topleft",
       c("Daily Deaths","Loess"),
       col=c("black","red"),
       lty = c(1, 1),
       cex = 0.8)

# plot(df$date,df$DailyDeaths,type="l",main="Daily COVID-19 Deaths(0.75)",col="black")
# lines(df$date,df$sm75,col="red")
# grid(col="black")
# legend("topleft",
#        c("Daily Deaths","Loess"),
#        col=c("black","red"),
#        lty = c(1, 1),
#        cex = 0.8)
```

### Weekly and Monthly COVID-19 Cases and Deaths

```{r}
df$Monthly <- as.Date(cut(df$date,
  breaks = "month"))
df$Weekly <- as.Date(cut(df$date,
  breaks = "week",
  start.on.monday = FALSE)) # changes weekly break point to Sunday

```

```{r}
weekly_cases <- aggregate(DailyCases~Weekly,data=df,FUN=sum)
weekly_deaths <- aggregate(DailyDeaths~Weekly,data=df,FUN=sum)
weekly_cases$RCases <- weekly_deaths$DailyDeaths / weekly_cases$DailyCases *100
```

```{r}
barplot(DailyCases ~Weekly,data=weekly_cases,main="Weekly COVOD-19 Cases",xlab="Weekly Date",ylab="Cases")
grid(col="black")

barplot(DailyDeaths ~Weekly,data=weekly_deaths,main="Weekly COVID-19 Deaths",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")
```


```{r}
monthly_cases <- aggregate(DailyCases~Monthly,data=df,FUN=sum)
monthly_deaths <- aggregate(DailyDeaths~Monthly,data=df,FUN=sum)
```

```{r}


# barplot(DailyDeaths ~Monthly,data=monthly_deaths,main="Monthly COVID-19 Deaths",
#         xlab="Weekbarplot(DailyCases ~Monthly,data=monthly_cases,main="Monthly COVOD-19 Cases",xlab="MonthlyDate",ylab="Cases")
# grid(col="black")ly Date",ylab="Deaths")
# grid(col="black")
```

## Plot of Estimated Weekly Death Rate
```{r}
barplot(RCases ~Weekly,data=weekly_cases,main="Estimated Weekly Death Rate",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")
```