---
title: "Oklahoma COVID-19 Random State"
author: "David J Jackson"
date: "8/21/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
df <- read.csv("./Oklahoma.csv")
df$date <- as.Date(df$date)
summary(df$DailyCases)
summary(df$DailyDeaths)

```

### Cumulative Totals Cases and Deaths

```{r}
plot(df$date,df$cases,type="l",main="Oklahoma's Cumulative Cases")
grid(col="black")
plot(df$date,df$deaths,type="l",main="Oklahoma's Cumulative Deaths")
grid(col="black")
```

### Daily Totals for Cases and Deaths

```{r}
plot(df$date,df$DailyCases,type="l",main="Oklahoma's Daily Cases")
grid(col="black")
plot(df$date,df$DailyDeaths,type="l",main="Oklahoma's Daily Deaths")
grid(col="black")
```

### Weekly and Monthly Cases and Deaths

```{r}
df$Month <- as.Date(cut(df$date,
  breaks = "month"))
df$Week <- as.Date(cut(df$date,
  breaks = "week",
  start.on.monday = FALSE)) # changes weekly break point to Sunday

```

```{r}
weekly_cases <- aggregate(DailyCases~Week,data=df,FUN=sum)
weekly_deaths <- aggregate(DailyDeaths~Week,data=df,FUN=sum)
```

```{r}
barplot(DailyCases ~Week,data=weekly_cases,main="Weekly COVOD-19 Cases",xlab="Weekly Date",ylab="Cases")
grid(col="black")

barplot(DailyDeaths ~Week,data=weekly_deaths,main="Weekly COVID-19 Deaths",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")
```


```{r}
monthly_cases <- aggregate(DailyCases~Month,data=df,FUN=sum)
monthly_deaths <- aggregate(DailyDeaths~Month,data=df,FUN=sum)
```

```{r}
barplot(DailyCases ~Month,data=monthly_cases,main="Monthly COVOD-19 Cases",xlab="MonthlyDate",ylab="Cases")
grid(col="black")

barplot(DailyDeaths ~Month,data=monthly_deaths,main="Monthly COVID-19 Deaths",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")
```





