---
title: "COVID-19 Ramdom States Analysis"
author: "David J Jackson"
date: "9/17/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSQLite)
library(ggplot2)
library(scales)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))

```

## Random States COVID-19 Analysis for Maine.

```{r}
# PUll State level data
rm(list=ls())
source("../DATA/movavg.R")

db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")

VI <- dbGetQuery(db,"select date,state,TotalCases,TotalDeaths,new_cases,new_deaths from  STATESDAILY where state='Maine'")
VI$date <- as.Date(VI$date)
VI$date <- sort(VI$date,decreasing = TRUE)
str(VI)
```

## County Data

```{r}
DF <- dbGetQuery(db,"select date,state,county,new_cases,new_deaths from  COUNTYDAILY where state='Maine'")
DF$date <- as.Date(DF$date)
str(DF$date)
```

## Plot Daily New Cases and New Deaths 
####  Cumulative Total Cases and Deaths

```{r}
ggplot(VI) +geom_line(aes(x=date,y=TotalCases)) +
  labs(title="Cumulative Cases by Date") 

ggplot(VI) +geom_line(aes(x=date,y=TotalDeaths)) +
  labs(title="Cumulative Deaths by Date") 
  
```

####  Daily Cases, Daily Deaths (w/ 14 Day Moving Avearge) by Date

```{r}
VI$MAC <- movingAverage(VI$new_cases,14)
VI$MAD <- movingAverage(VI$new_deaths,14)

ggplot(VI) +geom_line(aes(x=date,y=new_cases,col="Daily Cases")) + 
  geom_line(aes(x=date,y=MAC,col="Moving Avg")) +
  labs(title="Total Cases by Date") 

ggplot(VI) +geom_line(aes(x=date,y=new_deaths,col="Daily Deaths")) + 
  geom_line(aes(x=date,y=MAD,col="Moving Avg")) +
  labs(title="Total Deaths by Date") 

  
```

#### Weekly  New Cases and New Deaths.

```{r}
VI$Monthly <- as.Date(cut(VI$date,
  breaks = "month"))
VI$Weekly <- as.Date(cut(VI$date,
  breaks = "week",
  start.on.monday = FALSE)) # changes weekly break point to Sunday

```

```{r}
weekly_cases <- aggregate(new_cases~Weekly,data=VI,FUN=sum)
weekly_deaths <- aggregate(new_deaths~Weekly,data=VI,FUN=sum)
weekly_cases$RCases <- weekly_deaths$new_deaths / weekly_cases$new_cases *100
```

```{r}
ggplot(weekly_cases) + geom_col(aes(x=Weekly,y=new_cases)) +
  labs(title="Total Cases by Week")

ggplot(weekly_deaths) + geom_col(aes(x=Weekly,y=new_deaths)) +
  labs(title="Total Deaths by Week")
```

### Total New Cases and Deaths from Jun. 1, 2020 - Present

```{r}
df <- subset(VI,date >="2020-06-01")
ggplot(df) + geom_line(aes(x=date,y=new_cases)) +
  geom_smooth(aes(x=date,y=new_cases)) +
  labs(title="Current Spike in Deaths: Jun. 1, 2020 - Preesent")

df <- subset(VI,date >="2020-06-01")
ggplot(df) + geom_line(aes(x=date,y=new_deaths)) +
  geom_smooth(aes(x=date,y=new_deaths)) +
  labs(title="Current Spike in Deaths Jun. 1, 2020 - Present")
```

### Top 5 countries for last 7  days : Total Cases and Deaths

```{r}
df <- subset(DF,date >=Sys.Date() -8 )
Top <- df[order(df$new_cases,decreasing = TRUE),]
Top5 <-head(Top,n=5)
data <- aggregate(new_cases~county,data=Top5,FUN=sum)
## Time for a little ggplot action
ggplot(data) + geom_col(aes(x=county,y=new_cases)) +
  labs(title="Top Five County Ranked by Cases for Last Seven  Days",
       x="County",y="Total Cases",caption = "(Source: New York Times)")
```
```{r}
Topd <- df[order(df$new_deaths,decreasing = TRUE),]
Top5 <-head(Top,n=5)
data1<- aggregate(new_deaths~county,data=Top5,FUN=sum)
## Time for a little ggplot action
ggplot(data1) + geom_col(aes(x=county,y=new_deaths)) +
  labs(title="Top Five County Ranked by Deaths for Last Seven  Days",
       x="County",y="Total Deaths",caption = "(Source: New York Times)")

```
